Version =20
VersionRequired =20
Begin Form
    PopUp = NotDefault
    RecordSelectors = NotDefault
    FastLaserPrinting = NotDefault
    MinButton = NotDefault
    ShortcutMenu = NotDefault
    AutoCenter = NotDefault
    NavigationButtons = NotDefault
    DividingLines = NotDefault
    KeyPreview = NotDefault
    DataEntry = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =0
    ScrollBars =0
    ViewsAllowed =1
    TabularCharSet =177
    TabularFamily =0
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridY =10
    Width =8145
    DatasheetFontHeight =11
    ItemSuffix =1582
    Left =-18023
    Top =-18473
    Right =67
    Bottom =-8138
    RecSrcDt = Begin
        0x4a0577b4d2d8e540
    End
    Caption ="Create Task"
    DatasheetFontName ="Calibri"
    OnResize ="[Event Procedure]"
    OnLoad ="[Event Procedure]"
    AllowDatasheetView =0
    FilterOnLoad =0
    SplitFormDatasheet =1
    SplitFormDatasheet =1
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =255
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
    Begin
        Begin Label
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin Rectangle
            SpecialEffect =3
            BackStyle =0
            BorderLineStyle =0
            Width =850
            Height =850
            BorderShade =65.0
            GridlineShade =65.0
        End
        Begin Line
            BorderLineStyle =0
            Width =1701
            BorderThemeColorIndex =0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin CommandButton
            Width =1701
            Height =283
            FontSize =11
            FontWeight =400
            FontName ="Calibri"
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            UseTheme =1
            Shape =1
            Gradient =12
            BackThemeColorIndex =4
            BackTint =60.0
            BorderLineStyle =0
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
        End
        Begin OptionButton
            BorderLineStyle =0
            LabelX =230
            LabelY =-30
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin CheckBox
            BorderLineStyle =0
            LabelX =230
            LabelY =-30
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin OptionGroup
            SpecialEffect =3
            BorderLineStyle =0
            Width =1701
            Height =1701
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin BoundObjectFrame
            AddColon = NotDefault
            SizeMode =3
            SpecialEffect =2
            BorderLineStyle =0
            Width =4536
            Height =2835
            LabelX =-1701
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin TextBox
            AddColon = NotDefault
            FELineBreak = NotDefault
            BorderLineStyle =0
            Width =1701
            LabelX =-1701
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin ListBox
            BorderLineStyle =0
            Width =1701
            Height =1417
            LabelX =-1701
            FontSize =11
            FontName ="Calibri"
            AllowValueListEdits =1
            InheritValueList =1
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin ComboBox
            AddColon = NotDefault
            BorderLineStyle =0
            Width =1701
            LabelX =-1701
            FontSize =11
            FontName ="Calibri"
            AllowValueListEdits =1
            InheritValueList =1
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin Subform
            BorderLineStyle =0
            Width =1701
            Height =1701
            BorderThemeColorIndex =1
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            BorderShade =65.0
            ShowPageHeaderAndPageFooter =1
        End
        Begin UnboundObjectFrame
            SpecialEffect =2
            OldBorderStyle =1
            Width =4536
            Height =2835
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin PageBreak
            Width =283
        End
        Begin CustomControl
            OldBorderStyle =1
            Width =4536
            Height =2835
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin Tab
            Width =5103
            Height =3402
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            UseTheme =1
            Shape =3
            BackThemeColorIndex =1
            BackShade =85.0
            BorderLineStyle =0
            BorderThemeColorIndex =2
            BorderTint =60.0
            HoverThemeColorIndex =1
            PressedThemeColorIndex =1
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
        Begin Page
            Width =1701
            Height =1701
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin EmptyCell
            Height =240
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin NavigationControl
            BorderWidth =1
            BorderLineStyle =0
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin NavigationButton
            Width =283
            Height =283
            ForeColor =-2
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            HoverColor =-2
            HoverThemeColorIndex =2
            HoverTint =20.0
            PressedColor =-2
            PressedThemeColorIndex =2
            PressedTint =60.0
            HoverForeColor =-2
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeColor =-2
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
            BackThemeColorIndex =1
            OldBorderStyle =0
            BorderLineStyle =0
            BorderThemeColorIndex =3
            BorderShade =90.0
            ThemeFontIndex =1
            FontName ="Calibri"
            FontWeight =400
            FontSize =11
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
        Begin Section
            CanGrow = NotDefault
            CanShrink = NotDefault
            Height =5280
            Name ="Detalle"
            AlternateBackThemeColorIndex =4
            AlternateBackTint =40.0
            BackThemeColorIndex =3
            Begin
                Begin TextBox
                    Enabled = NotDefault
                    Locked = NotDefault
                    TabStop = NotDefault
                    EnterKeyBehavior = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =1
                    TextFontFamily =49
                    BackStyle =0
                    IMESentenceMode =3
                    Left =2910
                    Top =3000
                    Width =5070
                    Height =1440
                    FontSize =9
                    FontWeight =100
                    TabIndex =7
                    TopMargin =58
                    ForeColor =8355711
                    Name ="DS_TASK_TEXT_CONTENT"
                    FontName ="Consolas"
                    GroupTable =9
                    LeftPadding =0
                    TopPadding =119
                    RightPadding =0
                    BottomPadding =0
                    GridlineStyleTop =1
                    GridlineColor =10921638
                    TextFormat =1
                    ShowDatePicker =0

                    LayoutCachedLeft =2910
                    LayoutCachedTop =3000
                    LayoutCachedWidth =7980
                    LayoutCachedHeight =4440
                    ColumnEnd =1
                    LayoutGroup =8
                    BackThemeColorIndex =3
                    BorderThemeColorIndex =3
                    BorderShade =100.0
                    ThemeFontIndex =-1
                    ForeTint =50.0
                    GroupTable =9
                End
                Begin ComboBox
                    Visible = NotDefault
                    TabStop = NotDefault
                    RowSourceTypeInt =1
                    OverlapFlags =87
                    TextAlign =3
                    TextFontFamily =49
                    IMESentenceMode =3
                    Left =5535
                    Top =615
                    Width =2400
                    Height =330
                    FontSize =9
                    FontWeight =100
                    TabIndex =2
                    BorderColor =16777215
                    Name ="DS_TASK_PARAM_0"
                    RowSourceType ="Value List"
                    FontName ="Consolas"
                    OnChange ="[Event Procedure]"
                    GroupTable =3
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineStyleTop =1
                    GridlineStyleRight =1
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    HorizontalAnchor =2
                    AllowValueListEdits =0
                    LeftMargin =31
                    TopMargin =58
                    RightMargin =72

                    LayoutCachedLeft =5535
                    LayoutCachedTop =615
                    LayoutCachedWidth =7935
                    LayoutCachedHeight =945
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =2
                    ThemeFontIndex =-1
                    BorderShade =100.0
                    ForeThemeColorIndex =0
                    ForeTint =65.0
                    ForeShade =100.0
                    GroupTable =3
                    Begin
                        Begin Label
                            Visible = NotDefault
                            BackStyle =1
                            OldBorderStyle =1
                            OverlapFlags =93
                            TextAlign =1
                            Left =2895
                            Top =615
                            Width =2640
                            Height =330
                            FontSize =10
                            FontWeight =100
                            LeftMargin =113
                            TopMargin =40
                            RightMargin =57
                            ForeColor =5855577
                            Name ="DS_LABEL_TASK_PARAM_0"
                            GroupTable =3
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            GridlineStyleLeft =1
                            GridlineStyleTop =1
                            GridlineStyleBottom =1
                            GridlineColor =10921638
                            LayoutCachedLeft =2895
                            LayoutCachedTop =615
                            LayoutCachedWidth =5535
                            LayoutCachedHeight =945
                            LayoutGroup =2
                            BorderThemeColorIndex =1
                            BorderTint =100.0
                            ForeTint =65.0
                            GroupTable =3
                        End
                    End
                End
                Begin ComboBox
                    Visible = NotDefault
                    TabStop = NotDefault
                    RowSourceTypeInt =1
                    OverlapFlags =87
                    TextAlign =3
                    TextFontFamily =49
                    IMESentenceMode =3
                    Left =5535
                    Top =1065
                    Width =2400
                    Height =330
                    FontSize =9
                    FontWeight =100
                    TabIndex =3
                    BorderColor =16777215
                    Name ="DS_TASK_PARAM_1"
                    RowSourceType ="Value List"
                    FontName ="Consolas"
                    OnChange ="[Event Procedure]"
                    GroupTable =4
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineStyleTop =1
                    GridlineStyleRight =1
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    HorizontalAnchor =2
                    AllowValueListEdits =0
                    LeftMargin =31
                    TopMargin =58
                    RightMargin =72

                    LayoutCachedLeft =5535
                    LayoutCachedTop =1065
                    LayoutCachedWidth =7935
                    LayoutCachedHeight =1395
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =3
                    ThemeFontIndex =-1
                    BorderShade =100.0
                    ForeThemeColorIndex =0
                    ForeTint =65.0
                    ForeShade =100.0
                    GroupTable =4
                    Begin
                        Begin Label
                            Visible = NotDefault
                            BackStyle =1
                            OldBorderStyle =1
                            OverlapFlags =93
                            TextAlign =1
                            Left =2895
                            Top =1065
                            Width =2640
                            Height =330
                            FontSize =10
                            FontWeight =100
                            LeftMargin =113
                            TopMargin =40
                            RightMargin =57
                            ForeColor =5855577
                            Name ="DS_LABEL_TASK_PARAM_1"
                            GroupTable =4
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            GridlineStyleLeft =1
                            GridlineStyleTop =1
                            GridlineStyleBottom =1
                            GridlineColor =10921638
                            LayoutCachedLeft =2895
                            LayoutCachedTop =1065
                            LayoutCachedWidth =5535
                            LayoutCachedHeight =1395
                            LayoutGroup =3
                            BorderThemeColorIndex =1
                            BorderTint =100.0
                            ForeTint =65.0
                            GroupTable =4
                        End
                    End
                End
                Begin ComboBox
                    Visible = NotDefault
                    TabStop = NotDefault
                    RowSourceTypeInt =1
                    OverlapFlags =87
                    TextAlign =3
                    TextFontFamily =49
                    IMESentenceMode =3
                    Left =5535
                    Top =1515
                    Width =2400
                    Height =330
                    FontSize =9
                    FontWeight =100
                    TabIndex =4
                    BorderColor =16777215
                    Name ="DS_TASK_PARAM_2"
                    RowSourceType ="Value List"
                    FontName ="Consolas"
                    GroupTable =5
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineStyleTop =1
                    GridlineStyleRight =1
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    HorizontalAnchor =2
                    AllowValueListEdits =0
                    LeftMargin =31
                    TopMargin =58
                    RightMargin =72

                    LayoutCachedLeft =5535
                    LayoutCachedTop =1515
                    LayoutCachedWidth =7935
                    LayoutCachedHeight =1845
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =4
                    ThemeFontIndex =-1
                    BorderShade =100.0
                    ForeThemeColorIndex =0
                    ForeTint =65.0
                    ForeShade =100.0
                    GroupTable =5
                    Begin
                        Begin Label
                            Visible = NotDefault
                            BackStyle =1
                            OldBorderStyle =1
                            OverlapFlags =93
                            TextAlign =1
                            Left =2895
                            Top =1515
                            Width =2640
                            Height =330
                            FontSize =10
                            FontWeight =100
                            LeftMargin =113
                            TopMargin =40
                            RightMargin =57
                            ForeColor =5855577
                            Name ="DS_LABEL_TASK_PARAM_2"
                            GroupTable =5
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            GridlineStyleLeft =1
                            GridlineStyleTop =1
                            GridlineStyleBottom =1
                            GridlineColor =10921638
                            LayoutCachedLeft =2895
                            LayoutCachedTop =1515
                            LayoutCachedWidth =5535
                            LayoutCachedHeight =1845
                            LayoutGroup =4
                            BorderThemeColorIndex =1
                            BorderTint =100.0
                            ForeTint =65.0
                            GroupTable =5
                        End
                    End
                End
                Begin ComboBox
                    Visible = NotDefault
                    TabStop = NotDefault
                    RowSourceTypeInt =1
                    OverlapFlags =87
                    TextAlign =3
                    TextFontFamily =49
                    IMESentenceMode =3
                    Left =5535
                    Top =1965
                    Width =2400
                    Height =330
                    FontSize =9
                    FontWeight =100
                    TabIndex =5
                    BorderColor =16777215
                    Name ="DS_TASK_PARAM_3"
                    RowSourceType ="Value List"
                    FontName ="Consolas"
                    GroupTable =6
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineStyleTop =1
                    GridlineStyleRight =1
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    HorizontalAnchor =2
                    AllowValueListEdits =0
                    LeftMargin =31
                    TopMargin =58
                    RightMargin =72

                    LayoutCachedLeft =5535
                    LayoutCachedTop =1965
                    LayoutCachedWidth =7935
                    LayoutCachedHeight =2295
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =5
                    ThemeFontIndex =-1
                    BorderShade =100.0
                    ForeThemeColorIndex =0
                    ForeTint =65.0
                    ForeShade =100.0
                    GroupTable =6
                    Begin
                        Begin Label
                            Visible = NotDefault
                            BackStyle =1
                            OldBorderStyle =1
                            OverlapFlags =93
                            TextAlign =1
                            Left =2895
                            Top =1965
                            Width =2640
                            Height =330
                            FontSize =10
                            FontWeight =100
                            LeftMargin =113
                            TopMargin =40
                            RightMargin =57
                            ForeColor =5855577
                            Name ="DS_LABEL_TASK_PARAM_3"
                            GroupTable =6
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            GridlineStyleLeft =1
                            GridlineStyleTop =1
                            GridlineStyleBottom =1
                            GridlineColor =10921638
                            LayoutCachedLeft =2895
                            LayoutCachedTop =1965
                            LayoutCachedWidth =5535
                            LayoutCachedHeight =2295
                            LayoutGroup =5
                            BorderThemeColorIndex =1
                            BorderTint =100.0
                            ForeTint =65.0
                            GroupTable =6
                        End
                    End
                End
                Begin TextBox
                    Visible = NotDefault
                    Enabled = NotDefault
                    Locked = NotDefault
                    TabStop = NotDefault
                    EnterKeyBehavior = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =1
                    TextFontFamily =49
                    BackStyle =0
                    IMESentenceMode =3
                    Left =2910
                    Top =165
                    Width =5070
                    Height =345
                    FontSize =8
                    FontWeight =100
                    TabIndex =1
                    TopMargin =58
                    ForeColor =5026082
                    Name ="DS_TASK_DEFINITION_SYNTAX"
                    FontName ="Consolas"
                    GroupTable =7
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    TextFormat =1
                    ShowDatePicker =0

                    LayoutCachedLeft =2910
                    LayoutCachedTop =165
                    LayoutCachedWidth =7980
                    LayoutCachedHeight =510
                    ColumnEnd =1
                    LayoutGroup =6
                    BackThemeColorIndex =3
                    BorderThemeColorIndex =3
                    BorderShade =100.0
                    ThemeFontIndex =-1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =7
                End
                Begin ComboBox
                    Visible = NotDefault
                    TabStop = NotDefault
                    RowSourceTypeInt =1
                    OverlapFlags =87
                    TextAlign =3
                    TextFontFamily =49
                    IMESentenceMode =3
                    Left =5535
                    Top =2415
                    Width =2400
                    Height =330
                    FontSize =9
                    FontWeight =100
                    TabIndex =6
                    BorderColor =16777215
                    Name ="DS_TASK_PARAM_4"
                    RowSourceType ="Value List"
                    FontName ="Consolas"
                    GroupTable =8
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineStyleTop =1
                    GridlineStyleRight =1
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    HorizontalAnchor =2
                    AllowValueListEdits =0
                    LeftMargin =31
                    TopMargin =58
                    RightMargin =72

                    LayoutCachedLeft =5535
                    LayoutCachedTop =2415
                    LayoutCachedWidth =7935
                    LayoutCachedHeight =2745
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =7
                    ThemeFontIndex =-1
                    BorderShade =100.0
                    ForeThemeColorIndex =0
                    ForeTint =65.0
                    ForeShade =100.0
                    GroupTable =8
                    Begin
                        Begin Label
                            Visible = NotDefault
                            BackStyle =1
                            OldBorderStyle =1
                            OverlapFlags =93
                            TextAlign =1
                            Left =2895
                            Top =2415
                            Width =2640
                            Height =330
                            FontSize =10
                            FontWeight =100
                            LeftMargin =113
                            TopMargin =40
                            RightMargin =57
                            ForeColor =5855577
                            Name ="DS_LABEL_TASK_PARAM_4"
                            GroupTable =8
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            GridlineStyleLeft =1
                            GridlineStyleTop =1
                            GridlineStyleBottom =1
                            GridlineColor =10921638
                            LayoutCachedLeft =2895
                            LayoutCachedTop =2415
                            LayoutCachedWidth =5535
                            LayoutCachedHeight =2745
                            LayoutGroup =7
                            BorderThemeColorIndex =1
                            BorderTint =100.0
                            ForeTint =65.0
                            GroupTable =8
                        End
                    End
                End
                Begin Rectangle
                    SpecialEffect =0
                    BackStyle =1
                    OldBorderStyle =0
                    OverlapFlags =93
                    Top =4590
                    Width =8145
                    Height =690
                    BackColor =-2147483603
                    Name ="DS_FOOTER_BG"
                    GroupTable =10
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineStyleTop =1
                    VerticalAnchor =1
                    LayoutCachedTop =4590
                    LayoutCachedWidth =8145
                    LayoutCachedHeight =5280
                    LayoutGroup =9
                    GridlineThemeColorIndex =1
                    GridlineShade =50.0
                    GroupTable =10
                End
                Begin CommandButton
                    OverlapFlags =215
                    Left =6690
                    Top =4755
                    Width =1245
                    Height =360
                    FontSize =10
                    TabIndex =11
                    Name ="DS_ADD_TASK_BUTTON"
                    Caption ="ADD TASK"
                    OnClick ="[Event Procedure]"
                    GroupTable =11
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =15
                    BottomPadding =15
                    GridlineColor =10921638
                    HorizontalAnchor =1
                    VerticalAnchor =1

                    CursorOnHover =1
                    LayoutCachedLeft =6690
                    LayoutCachedTop =4755
                    LayoutCachedWidth =7935
                    LayoutCachedHeight =5115
                    LayoutGroup =10
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Shape =0
                    Gradient =0
                    BackThemeColorIndex =8
                    BackTint =100.0
                    BorderThemeColorIndex =8
                    BorderTint =100.0
                    BorderShade =50.0
                    ThemeFontIndex =-1
                    HoverThemeColorIndex =8
                    HoverTint =60.0
                    PressedThemeColorIndex =8
                    PressedTint =40.0
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeColor =5855577
                    PressedForeTint =65.0
                    GroupTable =11
                    QuickStyle =10
                    QuickStyleMask =-1009
                    Overlaps =1
                End
                Begin CommandButton
                    OverlapFlags =215
                    Left =5295
                    Top =4755
                    Width =1245
                    Height =360
                    FontSize =10
                    TabIndex =10
                    Name ="DS_CANCEL_BUTTON"
                    Caption ="CANCEL"
                    OnClick ="[Event Procedure]"
                    GroupTable =12
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =15
                    BottomPadding =15
                    GridlineColor =10921638
                    HorizontalAnchor =1
                    VerticalAnchor =1

                    CursorOnHover =1
                    LayoutCachedLeft =5295
                    LayoutCachedTop =4755
                    LayoutCachedWidth =6540
                    LayoutCachedHeight =5115
                    LayoutGroup =11
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Shape =0
                    Gradient =0
                    BackThemeColorIndex =8
                    BackTint =100.0
                    BorderThemeColorIndex =8
                    BorderTint =100.0
                    BorderShade =50.0
                    ThemeFontIndex =-1
                    HoverThemeColorIndex =8
                    HoverTint =60.0
                    PressedThemeColorIndex =8
                    PressedTint =40.0
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeColor =5855577
                    PressedForeTint =65.0
                    GroupTable =12
                    QuickStyle =10
                    QuickStyleMask =-1009
                    Overlaps =1
                End
                Begin Line
                    OverlapFlags =85
                    Top =15
                    Width =8145
                    Name ="DS_FORM_TOP_LINE"
                    GridlineColor =10921638
                    HorizontalAnchor =2
                    LayoutCachedTop =15
                    LayoutCachedWidth =8145
                    LayoutCachedHeight =15
                    BorderThemeColorIndex =1
                    BorderShade =50.0
                End
                Begin Subform
                    OverlapFlags =87
                    Left =495
                    Top =165
                    Width =2281
                    Height =4260
                    BorderColor =16777215
                    Name ="DS_CREATE_TASK_LIST"
                    SourceObject ="Form.DS_RICHTEXT_LIST"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =15
                    RightPadding =15
                    BottomPadding =0
                    GridlineStyleTop =1
                    GridlineStyleRight =1
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    VerticalAnchor =2

                    LayoutCachedLeft =495
                    LayoutCachedTop =165
                    LayoutCachedWidth =2776
                    LayoutCachedHeight =4425
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BorderShade =100.0
                    GroupTable =1
                    Begin
                        Begin Label
                            Vertical = NotDefault
                            BackStyle =1
                            OldBorderStyle =1
                            OverlapFlags =93
                            TextFontCharSet =177
                            TextFontFamily =0
                            Left =165
                            Top =165
                            Width =330
                            Height =4260
                            FontSize =10
                            FontWeight =100
                            LeftMargin =58
                            ForeColor =-2147483600
                            Name ="Etiqueta1782"
                            Caption ="  A V A I L A B L E   T A S K S"
                            FontName ="Calibri Light"
                            GroupTable =1
                            LeftPadding =0
                            TopPadding =15
                            RightPadding =0
                            BottomPadding =0
                            GridlineStyleLeft =1
                            GridlineStyleTop =1
                            GridlineStyleBottom =1
                            GridlineColor =10921638
                            VerticalAnchor =2
                            LayoutCachedLeft =165
                            LayoutCachedTop =165
                            LayoutCachedWidth =495
                            LayoutCachedHeight =4425
                            LayoutGroup =1
                            ThemeFontIndex =-1
                            BorderThemeColorIndex =1
                            BorderTint =100.0
                            ForeThemeColorIndex =-1
                            ForeTint =100.0
                            GroupTable =1
                        End
                    End
                End
                Begin CommandButton
                    OverlapFlags =215
                    Left =165
                    Top =4755
                    Width =1755
                    Height =360
                    FontSize =10
                    TabIndex =8
                    Name ="DS_ENABLE_ALL_TASKS_BUTTON"
                    Caption ="ENABLE ALL TASKS"
                    OnClick ="[Event Procedure]"
                    GroupTable =13
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =15
                    BottomPadding =15
                    GridlineColor =10921638
                    VerticalAnchor =1

                    CursorOnHover =1
                    LayoutCachedLeft =165
                    LayoutCachedTop =4755
                    LayoutCachedWidth =1920
                    LayoutCachedHeight =5115
                    LayoutGroup =12
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Shape =0
                    Gradient =0
                    BackThemeColorIndex =8
                    BackTint =100.0
                    BorderThemeColorIndex =8
                    BorderTint =100.0
                    BorderShade =50.0
                    ThemeFontIndex =-1
                    HoverThemeColorIndex =8
                    HoverTint =60.0
                    PressedThemeColorIndex =8
                    PressedTint =40.0
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeColor =5855577
                    PressedForeTint =65.0
                    GroupTable =13
                    QuickStyle =10
                    QuickStyleMask =-1009
                    Overlaps =1
                End
                Begin CommandButton
                    OverlapFlags =215
                    Left =2115
                    Top =4755
                    Width =1440
                    Height =360
                    FontSize =10
                    TabIndex =9
                    Name ="DS_SHOW_CUSTOM_VARS_BUTTON"
                    Caption ="SHOW C. VARS"
                    OnClick ="[Event Procedure]"
                    GroupTable =13
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =15
                    BottomPadding =15
                    GridlineColor =10921638
                    VerticalAnchor =1

                    CursorOnHover =1
                    LayoutCachedLeft =2115
                    LayoutCachedTop =4755
                    LayoutCachedWidth =3555
                    LayoutCachedHeight =5115
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =12
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Shape =0
                    Gradient =0
                    BackThemeColorIndex =8
                    BackTint =100.0
                    BorderThemeColorIndex =8
                    BorderTint =100.0
                    BorderShade =50.0
                    ThemeFontIndex =-1
                    HoverThemeColorIndex =8
                    HoverTint =60.0
                    PressedThemeColorIndex =8
                    PressedTint =40.0
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeColor =5855577
                    PressedForeTint =65.0
                    GroupTable =13
                    QuickStyle =10
                    QuickStyleMask =-1009
                    Overlaps =1
                End
                Begin EmptyCell
                    Left =1935
                    Top =4755
                    Width =165
                    Height =360
                    Name ="CeldaVacía1579"
                    GroupTable =13
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =15
                    BottomPadding =15
                    GridlineColor =10921638
                    VerticalAnchor =1
                    LayoutCachedLeft =1935
                    LayoutCachedTop =4755
                    LayoutCachedWidth =2100
                    LayoutCachedHeight =5115
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =12
                    GroupTable =13
                End
            End
        End
    End
End
CodeBehindForm
' See "DS_CREATE_TASK.cls"
